version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_DB=POSTGRES_DB